name: japanfoods
favicon: null
layout_spectrum: 0.51173
typography_spectrum: 0.14151344215497375
title: All about Japanese food
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5723485324997455
  lightness: 0.36373060778714716
  saturation: 0.09676305763423443
  rhythmicContrast: 0.6104194119106978
purpose: []
